# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://amazonsearch.netlify.app/"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

